### PR TITLE
Fix edit link on What's New pages

### LINKED ISSUE #401: what's new post edit this page button links the what's new.js template not the actual markdown page
The edit this page button on the what's new post pages should link the actual MD page for editing, not the template page. 

go to a what's new post, click on edit this page, you will be taken here: 

https://github.com/newrelic/docs-website/blob/develop/src/templates/whatsNew.js

Where a user should be routed here: 

https://github.com/newrelic/docs-website/blob/develop/src/content/whats-new/2020/12/alerts-applied-intelligence-new-landing-page.md

### PR DESCRIPTION
**Pull request by roadlittledawn**
Closes #401 

Generates `fileRelativePath` from `fileAbsolutePath` in `markdownRemark` nodes and adds it to the context which is then used in the footer to populate the Edit this page link.

### CODE REVIEW

File: gatsby-node.js [hunk 1]
```diff
@@ -137,15 +138,18 @@ exports.createPages = async ({ actions, graphql, reporter }) => {
 
   allMarkdownRemark.edges.forEach(({ node }) => {
     const {
+      fileAbsolutePath,
       frontmatter: { template },
       fields: { slug },
     } = node;
+    const fileRelativePath = fileAbsolutePath.match(/src\/.*/g)[0];
```
Comment (jerelmiller) [inline gatsby-node.js:145]: We've been using [this function](https://github.com/newrelic/gatsby-theme-newrelic/blob/develop/packages/gatsby-theme-newrelic/gatsby-node.js#L131-L132) to get the relative path from the absolute path. Should we be consistent?

**Review by jerelmiller — COMMENTED** [review]
Just a single question, otherwise this looks great.

File: gatsby-node.js (hunk 1 above)
Comment (roadlittledawn) [reply gatsby-node.js:145]: oh right. i saw that earlier, but spaced it when i got it working. but yeah, makes sense to me to use and be consistent

File: gatsby-node.js [hunk 2]
```diff
@@ -146,6 +148,7 @@ exports.createPages = async ({ actions, graphql, reporter }) => {
       component: path.resolve(`${TEMPLATE_DIR}${template}.js`),
       context: {
         slug,
+        fileRelativePath: getFileRelativePath(fileAbsolutePath),
```
Comment (zstix) [inline gatsby-node.js:151]: I think we need to define or import `getFileRelativePath`

Comment (roadlittledawn) [reply gatsby-node.js:151]: we have a similar function in that file as well as the theme ¯\_(ツ)_/¯

**Review by jerelmiller — APPROVED** [review]

File: gatsby-node.js (hunk 2 above)
Comment (jerelmiller) [reply gatsby-node.js:151]: @zstix looks like it was defined at the bottom of this file already.
