### PR TITLE
Fix JP bugs and whats new json images 

### LINKED ISSUE #1016: azure-integrations-list page leads to a 404 page on Japanese site
### Description

Page renders 404.

### Steps to reproduce

1. Go to: https://docs-preview.newrelic.com/jp/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/

### Expected behavior

Page displays correctly in english as an page in JP that doesn't have a translation counterpart, should display in English

### Screenshots

N/A

### Additional context

N/A

### Environment

N/A

### LINKED ISSUE #1017: Japanese [For more help] section links send to US Docs site
### Description

All the links sending to docs articles in the [For more help] section send the user to the US docs site.

### Steps to reproduce

1. Go to https://docs-preview.newrelic.com/jp/docs/using-new-relic/welcome-new-relic/get-started/get-outage-information-statusnewreliccom
2. Click on any docs link within the [For more help] section (not developer link)

### Expected behavior

User is being linked to Japanese pages or pages on Japanese site.

### Screenshots

N/A

### Additional context

N/A

### Environment

N/A

### LINKED ISSUE #1064: Include absolute paths for images in Whats new JSON
## Description
In order for images to be displayed correctly within the product, we should use _absolute_ image paths, not relative ones when constructing the JSON that the product consumes.

### PR DESCRIPTION
**Pull request by caylahamann**
## PR to fix a bunch of bugs

closes #1016 uses the localized redirect function to create redirects for auto-indexed pages
closes #1064 creates a visitor to add the absolute file path to the url 
closes #1017 uses the link component to account for localized paths in the DefaultRelatedContent section

### CODE REVIEW

**Review by jerelmiller — APPROVED** [review]
Nice work!

**Comment by caylahamann** [comment]
Going to wait til it builds! then I'll merge it in :)

File: gatsby-config.js [hunk 1]
```diff
@@ -1,5 +1,9 @@
 const fs = require('fs');
 const path = require('path');
+const parse = require('rehype-parse');
+const unified = require('unified');
+const addAbsoluteImagePath = require('./rehype-plugins/utils/addAbsoluteImagePath.js');
```
Comment (jerelmiller) [inline gatsby-config.js:5]:
```suggestion
const addAbsoluteImagePath = require('./rehype-plugins/utils/addAbsoluteImagePath');
```

**Review by jerelmiller — APPROVED** [review]
