### PR TITLE
Keep var/mark tags in documents

### LINKED ISSUE #670: Old What's New URLs not mapped on new site
### Description

The old WN posts use a different URL structure than the new site. Compare:

* https://docs.newrelic.com/whats-new/new-relic-lambda-extension
* https://docs-preview.newrelic.com/whats-new/2020/11/new-relic-lambda-extension

The old URLs, however, are broken when you map them to the new site:

* https://docs-preview.newrelic.com/whats-new/new-relic-lambda-extension

### Expected behavior

Create redirects for existing WN URLs

### PR DESCRIPTION
**Pull request by jerelmiller**
Closes #670 
Partially addresses #116

# Description

Migrates all `<var>` and `<mark>` tags into the docs. Note this does **NOT** migrated `<var>` and `<mark>` tags inside of code blocks. This will be done inside a followup PR. 

This PR also fixes issues with pages that redirect to themself. During our migraiton, we were pulling in redirects and attaching them to a matching page. This confused Gatsby because we had both a page and redirect created for the same location.

## Screenshots

**var**

Screen Shot 2021-01-29 at 5 57 55 PM

**mark**

Screen Shot 2021-01-29 at 5 57 59 PM

### CODE REVIEW

File: scripts/utils/migrate/html-to-markdown.js [hunk 1]
```diff
@@ -193,6 +193,14 @@ module.exports = (file) => {
       filter: (node) => node.nodeName === 'I' && node.classList.contains('fa'),
       replacement: (content, node) =>
         htmlToJSXConverter.convert(node.outerHTML),
+    })
+    .addRule('var/mark', {
+      filter: ['var', 'mark'],
+      replacement: (content, node) => {
+        const tag = node.nodeName.toLowerCase();
+
+        return `<${tag}>${content}</${tag}>`;
```
Comment (caylahamann) [inline scripts/utils/migrate/html-to-markdown.js:202]: how is this different than just returning the node ( `<var>` or `<mark>` ))?

File: gatsby-node.js [hunk 2]
```diff
@@ -90,6 +90,16 @@ exports.createPages = async ({ actions, graphql, reporter }) => {
         }
       }
 
+      whatsNewPosts: allMarkdownRemark(
+        filter: { fileAbsolutePath: { regex: "/src/content/whats-new/" } }
```
Comment (caylahamann) [inline gatsby-node.js:94]: I'm also gathering this has some redirect work! would you be able to explain what is going on here? or maybe a separate PR for the redirect stuff?

**Review by caylahamann — COMMENTED** [review]
Just two comments! overall it looks good to me (for the var/mark work, I'm not sure about the redirect stuff because i'm not sure what problem is being solved)

File: gatsby-node.js (hunk 2 above)
Comment (caylahamann) [reply gatsby-node.js:94]: Nevermind! I just read the full PR! Sorry about that

**Review by caylahamann — APPROVED** [review]

File: scripts/utils/migrate/html-to-markdown.js (hunk 1 above)
Comment (jerelmiller) [reply scripts/utils/migrate/html-to-markdown.js:202]: In this case, I'm filtering this rule by both `var` and `mark`. The `replacement` function doesn't know which is which when it is called, so this just makes sure that it takes the `nodeName` and uses that as the tag. The alternative was this (which didn't feel any better)

```js
return node.nodeName.toLowerCase() === 'var' ? `<var>${content}</var>` : `<mark>${content}</mark>`
```

File: gatsby-node.js (hunk 2 above)
Comment (jerelmiller) [reply gatsby-node.js:94]: Ah right, I kinda snuck in a separate ticket in this PR. This fixes #670 to make sure the old whats new URLs map to the new ones. I did this work in this PR because this PR [was failing](https://github.com/newrelic/docs-website/actions/runs/522497102) due to some weird cache issues from deleting all of the data dictionary stuff. By changing `gatsby-node`, this force-cleared the cache and allowed this PR to build successfully. Sorry about the confusion here!
