### PR TITLE
Keep captions and fix landing page layout

### LINKED ISSUE #586: Update layout on landing pages
## Description

Now that we have images rendered in the site (#582), the landing pages need a format similar to the current docs site. Right now, the docs preview site renders the image in the same column as the introductory paragraph.

Screen Shot 2021-01-19 at 10 05 28 AM

This should be rendered as a 2-column layout instead.

Screen Shot 2021-01-19 at 10 05 42 AM

### LINKED ISSUE #786: Image Captions are hard to distiguinsh from page text
### Description

On the current docs site, image captions have their own styling. This ensures they don't blend in with the surrounding text and confuse readers.

### Screenshots

The preview site makes it hard to see the relationship between the caption and the image. Compare:

_Drupal site_
image

_Preview site_
image

### Additional context

Labeling as a launch-blocker because if we don't fix this by launch, we'll lose the formatting that tells us which text is supposed to be image captions and which is running text.

### PR DESCRIPTION
**Pull request by jerelmiller**
Closes #586
Closes #786
Partially addresses #497 

# Description

* Update migration script to wrap image captions in a `figcaption` element
* Update landing page layout to use 2-column look like in the current docs site
* Add custom remark plugin to remove paragraph from button
* Minor mobile style fixes on landing pages
* Adds fso and tdp landing pages with lorem ipsum

## Screenshots

localhost_8000_docs_apm_size=n_10_n

### CODE REVIEW

File: codemods/landingPageHero.js [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+};
+
+// This codemod assumes it is run after the landing page tile grid has been run
+const landingPageHero = () => (tree, file) => {
+  if (file.data.doc.type !== 'landing_page') {
+    return;
+  }
+
+  visit(tree, 'root', (root) => {
+    const frontmatterIdx = 0; // frontmatter always comes first
```
Comment (zstix) [inline codemods/landingPageHero.js:19]: If frontmatter always comes first, is there any advantage to just writing `.slice(1, gridIdx)` below? I'm not against it...just curious if we gain anything by attaching some context to `0`.

File: scripts/utils/migrate/taxonomy-redirects.js [hunk 2]
```diff
@@ -25,8 +25,6 @@ const getTaxonomyPath = async (uri) => {
 
     return get(json, 'terms[0].term.urlPath');
   } catch (error) {
-    console.log(`Taxonomy ID ${id} does not exist, skipping`);
```
Comment (zstix) [inline scripts/utils/migrate/taxonomy-redirects.js:28]: 😅 Ooops! Thanks for removing this.

**Review by zstix — APPROVED** [review]
One minor question, but it's more of a curiosity.

File: codemods/landingPageHero.js (hunk 1 above)
Comment (jerelmiller) [reply codemods/landingPageHero.js:19]: Not sure. `1` felt like a magic number to me, hence why I opted for the variable. That being said, this was probably more of a long-term strategy than it needs to be. This codemod really only needs to survive until GA. I'll go ahead and switch to use `1`. If this were something that stuck around for the lifetime of the application, I'd probably opt for this so that updating this 6 months from now was obvious was that `1` was for 😄

**Review by zstix — APPROVED** [review]
